sudo: false
os: trusty
cache: false
language: java
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
      - SFURL=https://test.salesforce.com
before_install:
  - mkdir sfdx
script: ant -Dtest.level=RunLocalTests test