language: python
python: "2.7"
sudo: false
branches:
     only:
          - master
before_script: ./build/scripts/setup_credentials.sh
script: 
  - chmod a+x build/scripts/*
  - ./build/scripts/deploy.sh